name: Build KPM
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4
      - name: build kpm
        uses: APatchTeam/kpm-build-action@main
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/*.kpm
